dist: xenial
language: ruby
rvm:
  - 2.6.3
  - 2.7.0
  - jruby-9.2.7.0
  - jruby-9.2.11.0
env:
  global:
    - CC_TEST_REPORTER_ID=620ccc237826a7e38f89dcde46a9f014fc5848700ebe3b976296b5324e4f3f22
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
