# frozen_string_literal: true

require 'spec_helper'

describe 'comparing against a well-known location full of documents generated by solrmarc' do
  let(:indexer) do
    Traject::Indexer.new.tap do |i|
      i.load_config_file('./lib/traject/config/folio_config.rb')
    end
  end

  let(:record) { MARC::XMLReader.new(StringIO.new(marcxml)).to_a.first }
  let(:copy_fields) do
    %w[collection_search pub_date_search db_az_subject_search instructor course topic_display subject_other_display
       title_variant_display summary_display pub_display]
  end
  let(:ignored_fields) do
    %w[all_search created last_updated format _version_ author_sort callnum_facet_hsim marcbib_xml marcxml mhld_display fund_facet building_facet collection] + copy_fields
  end
  let(:pending_fields) { %w[reverse_shelfkey shelfkey preferred_barcode item_display date_cataloged access_facet] }
  subject(:result) { indexer.map_record(folio_record).transform_values { |v| v.sort } }
  let(:folio_record) { marc_to_folio(record) }

  let(:holding_data) do
    # rubocop:disable Layout/LineLength
    { 'a7096288' => [{ call_number: 'DG70 .P7 W77 2007', home_location: 'STACKS', current_location: nil, library: 'GREEN', scheme: 'LC', barcode: '36105123307642' }],
      'a12000520' => [{ call_number: 'JZ1310 .R46 2017', home_location: 'STACKS', current_location: nil, library: 'GREEN', scheme: 'LC', barcode: '36105225395669' }],
      'a24200' => [{ call_number: '868.4 .H899LA', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105044915473' }],
      'a31341' => [{ call_number: '281.9 .A781PM', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105046826009' }],
      'a7097007' => [{ call_number: 'EPRI NP-1570 V.1', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105129611187' }, { call_number: 'EPRI NP-1570 V.2', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105129611179' }],
      'a12006180' => [{ call_number: 'INTERNET RESOURCE', home_location: 'INTERNET', current_location: nil, library: 'SUL', scheme: 'ASIS', barcode: '12006180-1001' }],
      'a26883' => [{ call_number: 'PQ8519 .M213 E4', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033482840' }],
      'a7096181' => [{ call_number: 'PR6114 .A35 L66 2007', home_location: 'STACKS', current_location: nil, library: 'GREEN', scheme: 'LC', barcode: '36105123309457' }],
      'a12000222' => [{ call_number: 'NK3638 .K56 A4 2000', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105222297884' }],
      'a47981' => [{ call_number: '331.9074 .K15 NO.89', home_location: 'SEE-OTHER', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '47981-2001' }],
      'a20279' => [{ call_number: '472 .W158', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105047738104' }],
      'a39562' => [{ call_number: 'F2581 .M68', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033500658' }],
      'a25184' => [{ call_number: 'F2845 .P56', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033472817' }],
      'a7070581' => [{ call_number: 'S471 .C62 I568 2006', home_location: 'CHINESE', current_location: nil, library: 'EAST-ASIA', scheme: 'LC', barcode: '36105129913419' }],
      'a43871' => [{ call_number: 'AS182 .H125 1966:V.26', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033522975' }],
      'a32038' => [{ call_number: '914.472 .L628P', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048600121' }],
      'a43228' => [{ call_number: 'PA8118 .I5 S3 V.3', home_location: 'STACKS', current_location: nil, library: 'GREEN', scheme: 'LC', barcode: '36105033519245' }],
      'a36560' => [{ call_number: '297 .K842SA', home_location: 'PAGE-SP', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105025612040' }],
      'a43716' => [{ call_number: '330.92 .K94M', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105047262766' }],
      'a34351' => [{ call_number: '917.9 .R956', home_location: 'STACKS', current_location: nil, library: 'SAL', scheme: 'DEWEY', barcode: '36105048657089' }],
      'a44964' => [{ call_number: '330.954 .R313', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105047275958' }],
      'a20815' => [{ call_number: '492 .D784', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105047754911' }],
      'a29763' => [{ call_number: '282.1 .F825C', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105046830027' }],
      'a12005356' => [{ call_number: 'AMA PUBL GROUP', home_location: 'ASK@LANE', current_location: nil, library: 'LANE-MED', scheme: 'LC', barcode: 'LL328803' }],
      'a16671' => [{ call_number: '204 .S855', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105019985089' }],
      'a21608' => [{ call_number: '094.442 .B334B', home_location: 'SOUTH-MEZZ', current_location: nil, library: 'SAL', scheme: 'DEWEY', barcode: '36105128988354' }],
      'a29931' => [{ call_number: '910 .B974', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048551472' }, { call_number: '910 .B974', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048551480' }],
      'a11065' => [{ call_number: '135.2 .D372', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105046653627' }],
      'a14883' => [{ call_number: '224.1 .K36', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105020071994' }],
      'a7000325' => [{ call_number: 'DK508.9 .K78 C745 1960Z', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105129616095' }],
      'a12002011' => [{ call_number: 'INTERNET RESOURCE', home_location: 'INTERNET', current_location: nil, library: 'SUL', scheme: 'ASIS', barcode: '12002011-1001' }],
      'a3500626' => [{ call_number: 'M1112 .A336 OP.10 NO.12 1996', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105017303723' }],
      'a3503542' => [{ call_number: 'PS3563 .A67 R43 1996', home_location: 'STACKS', current_location: nil, library: 'GREEN', scheme: 'LC', barcode: '36105020713389' }],
      'a38116' => [{ call_number: '842.05 .P48 NO.21', home_location: 'SEE-OTHER', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '38116-2001' }],
      'a43508' => [{ call_number: '330.91 .J35', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105047260786' }],
      'a39408' => [{ call_number: 'F2581 .S3', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033499786' }],
      'a35203' => [{ call_number: '919.11 .H474I', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048674175' }],
      'a3504435' => [{ call_number: 'D2009 .S245 1997', home_location: 'SAL-PAGE', current_location: nil, library: 'SAL', scheme: 'LC', barcode: '36105070697011' }],
      'a6412' => [{ call_number: 'UNCLAAA6821', home_location: 'RECORDINGS', current_location: nil, library: 'ARS', scheme: 'ASIS', barcode: '001AAA6821' }, { call_number: 'MD 3657', home_location: 'PAGE-LP', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105011299257' }],
      'a7046041' => [{ call_number: 'CALIF E1950 .R4 NO.881M 1974:SUPPL.', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105005778845' }, { call_number: 'CALIF E1950 .R4 NO.881M 1970/1972:SUPPL.', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105126951651' }, { call_number: 'CALIF E1950 .R4 NO.881M 1970/1972', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105005778878' }, { call_number: 'CALIF E1950 .R4 NO.881M 1970/1971', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'ALPHANUM', barcode: '36105113722453' }],
      'a48334' => [{ call_number: 'DK401 .P895 V.21:PT.2', home_location: 'SEE-OTHER', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '001AAF0578' }],
      'a12007015' => [{ call_number: 'INTERNET RESOURCE', home_location: 'INTERNET', current_location: nil, library: 'SUL', scheme: 'ASIS', barcode: '12007015-1001' }],
      'a12003712' => [{ call_number: 'Q603 .H47 1960', home_location: 'ASK@LANE', current_location: nil, library: 'LANE-MED', scheme: 'LC', barcode: 'LL112120' }],
      'a12001577' => [{ call_number: 'INTERNET RESOURCE', home_location: 'INTERNET', current_location: nil, library: 'SUL', scheme: 'ASIS', barcode: '12001577-1001' }],
      'a48749' => [{ call_number: 'P25 .P4 V.27', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105033528972' }],
      'a16573' => [{ call_number: '252 .R649SR', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105010340714' }],
      'a28142' => [{ call_number: '901.2 .J79', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048536309' }, { call_number: '901.2 .J79', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'DEWEY', barcode: '36105048536317' }],
      'a6295' => [{ call_number: 'UNCLAAA6697', home_location: 'RECORDINGS', current_location: nil, library: 'ARS', scheme: 'ASIS', barcode: '001AAA6697' }],
      'a7045704' => [{ call_number: 'PN6222 .A3 N39 2000Z', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105128770034' }],
      'a14161' => [{ call_number: 'BD161 .P72', home_location: 'STACKS', current_location: nil, library: 'SAL3', scheme: 'LC', barcode: '36105000254214' }] }
    # rubocop:enable Layout/LineLength
  end

  Dir.glob(File.expand_path('solrmarc_example_docs/*', file_fixture_path)).each do |fixture|
    context "with #{fixture}" do
      before do
        holdings = holding_data[folio_record.instance_id].map { |data| build(:holding, data) }
        allow(folio_record).to receive(:sirsi_holdings).and_return(holdings)
      end

      let(:file) { File.read(fixture) }
      let(:data) { JSON.parse(file) }
      let(:solrmarc_doc) { data['doc'] }
      let(:expected_doc) do
        data['doc'].transform_values { |v| Array(v).map(&:to_s).sort }
      end
      let(:marcxml) { solrmarc_doc['marcxml'] }

      it 'maps the same general output' do
        # Stub the year so this test doesn't fail every January
        allow_any_instance_of(Time).to receive(:year).and_return(2019)
        expect(result).to include expected_doc.reject { |k, _v| (ignored_fields + pending_fields).include? k }
      end

      it 'maps the same general output' do
        skip unless pending_fields.any?
        pending
        expect(result.select { |k, _v| pending_fields.include? k }).to include expected_doc.select { |k, _v|
                                                                                 pending_fields.include? k
                                                                               }
        expect(false).to eq true # keep rspec happy if the above happens to pass
      end

      it 'maps collection' do
        # FOLIO add 'folio' to the list
        expect(result['collection']).to include(*expected_doc['collection'])
      end

      it 'maps building_facet' do
        # Some buildings change display names in FOLIO
        expect(result['building_facet']).to eq(expected_doc['building_facet']&.map do |x|
          case x
          when 'SAL1&2 (on-campus shelving)' then 'SAL1&2 (on-campus storage)'
          when 'Medical (Lane)' then 'Lane Medical'
          else
            x
          end
        end)
      end
    end
  end
end
